/*
 * To change this license header, choose License Headers in Project Properties
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CompanyFinance;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class DisplayEmployee extends javax.swing.JPanel {

    /**
     * Creates new form DisplayEmployee
     */
    DefaultTableModel dtm;
    public DisplayEmployee() {
        initComponents();
        dtm=(DefaultTableModel)jTable1.getModel();
        dtm.setRowCount(0);
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Loaded");
        } catch (Exception e) {
            System.out.println("Driver not Loaded");
        }
        Connection con=null;
        try {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/financial_management", "root", "");
            System.out.println("Database connected Sucessfully");
        } catch (Exception e) {
            System.out.println("Database not connected");
        }
        String sql="SELECT * FROM employee";
        Statement st=null;
        try {
            st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
             dtm.addRow(new Object[]{rs.getInt("Eid"),rs.getString("FirstName"),
                 rs.getString("MiddleName"),rs.getString("LastName"),rs.getString("Gender"),
                 rs.getString("Address"),rs.getString("City"),rs.getString("Phone"),rs.getString("Email"),
                 rs.getString("Level"),rs.getString("Field")});
            } System.out.println("Data Displayed");
            
        } catch (Exception e) {
            System.out.println("Data not Displayed"+e);
        }
        
        
    }

    /**n
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Display Registered Employee", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(0, 0, 0))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1010, 750));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Eid", "Firstname", "Middlename", "Lastname", "Gender", "Address", "City", "Email", "Level", "Field"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/deleteUser.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/editUser.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(143, 143, 143)
                .addComponent(jButton1)
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int noofselectedrows=jTable1.getSelectedRowCount();
        if(noofselectedrows==1)
        {
            int rowno=jTable1.getSelectedRow();
            Object eid=jTable1.getValueAt(rowno,0);
            try{
                Class.forName("com.mysql.jdbc.Driver");
                System.out.println("driver loaded");
            }catch(Exception e){
                System.out.println("driver not loaded");
            }
            Connection con=null;
            try{
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Financial_Management","root","");
                System.out.println("database connectedsuccesfully");
        }catch(Exception e){
                System.out.println("database not connected");
        }
            Statement st=null;
            String sql="DELETE FROM employee WHERE eid = "+eid;
            try{
                st=con.createStatement();
                st.executeUpdate(sql);
                dtm.removeRow(rowno);
                System.out.println("data deleted");
            }catch(Exception e){
                System.out.println("data not deleted");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 int noofselectedrows=jTable1.getSelectedRowCount();
        if(noofselectedrows==1){
            int rowno=jTable1.getSelectedRow();
            Object eid=jTable1.getValueAt(rowno,0);
            MainFrame.ChangePanel(new EditEmployee(eid));
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
